# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

variables:
  solution: 'Landorphan.Ioc.ServiceLocation.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  NUGET_AUTHORS: 'Landorphan LLC, Michael Prochaska, Timothy Stockstill'
  NUGET_OWNERS: 'landorphan, mprochaska, tstockstill'
  NUGET_LICENSE: 'MIT'
  NUGET_COPYRIGHT: 'Copyright © 2019 - Landorphan, LLC.'

stages:
  - stage: win_build
    displayName: Windows Build
    dependsOn: 
    jobs:
    - job: setup
      displayName: Setup System for Code Signing
      dependsOn: []
      pool:
        vmImage: 'windows-latest'
      steps:
      - template: build/az-build/prep-env.yml
      - template: build/az-build/prep-sign.yml
      - template: build/az-build/alter-version.yml
      - template: build/az-build/alter-sign.yml

    # - job: system_diagnostics
    #   displayName: Output System diagnostics
    #   dependsOn: setup
    #   variables:
    #     LNDF_VER: $[ dependencies.setup.outputs['set_version.LNDF_VER'] ]
    #     LNDF_VER_FULL: $[ dependencies.setup.outputs['set_veersion_full.LNDF_VER_FULL'] ]
    #     DS_PK: $[ dependencies.setup.outputs['get_delay_key.DS_PK'] ]
    #   pool:
    #     vmImage: 'windows-latest'
    #   steps:
    #   - script: |
    #       echo Write your commands here
    #       mkdir "$(Build.BinariesDirectory)/raw-build"
    #       dir "$(Build.BinariesDirectory)/raw-build"
    #       set
          
    #       echo "%DS_PK%"
    #       echo ""
    #       echo "Build Version: %DS_VER$"
    #       echo "Full Build Version: %DS_VER_FULL%"
    #       echo ""
    #       echo "dotnet --list-runtimes"
    #       dotnet --list-runtimes
    #       echo ""
    #       echo ""
    #       echo "dotnet --list-sdks"
    #       dotnet --list-sdks
    #       echo ""
    #       echo ""
    #       echo Use the environment variables input below to pass secret variables to this script
    #     displayName: 'Display Environment Info & Setup'

    #   - script: error 

    #   # - task: eliostruyf.build-task.custom-build-task.file-creator@2
    #   #   displayName: 'Create sign.cs File'
    #   #   inputs:
    #   #     fileoverwrite: true
    #   #     filepath: '$(Build.SourcesDirectory)\sign.cs'
    #   #     filecontent: |
    #   #       using System.Reflection;
            
    #   #       [assembly:AssemblyKeyFileAttribute(@"$(Agent.TempDirectory)\Landorphan-Light.snk")]

    #   - task: DownloadSecureFile@1
    #     inputs:
    #       secureFile: 'Landorphan-Light.snk'

    #   - script: |
    #       echo Write your commands here

    #       dir %BUILD_SOURCESDIRECTORY%   
    #       dir %BUILD_BINARIESDIRECTORY%
    #       dir d:\a\_temp
    #       cat %BUILD_SOURCESDIRECTORY%\sign.cs
    #       dir "$(Agent.BuildDirectory)\d"
          
    #       echo Use the environment variables input below to pass secret variables to this script
    #     displayName: 'Display Directory Info'

    # - job: core_build
    #   displayName: Run the core build
    #   dependsOn: setup
    #   pool:
    #     vmImage: 'windows-latest'
    #   steps:
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            # Write your commands here
            
            ls
            
      - task: NuGetToolInstaller@1
        displayName: Download most recent NuGet Tools

      - task: NuGetCommand@2
        inputs:
          restoreSolution: '$(solution)'

      - task: VSBuild@1
        displayName: 'Build solution **/Landorphan.Ioc.ServiceLocation.sln'
        inputs:
          solution: '**/Landorphan.Ioc.ServiceLocation.sln'
          platform: '$(BuildPlatform)'
          configuration: '$(BuildConfiguration)'
          
      - task: Bash@3
        displayName: 'Create list of output assemblies for code signing'
        inputs:
          targetType: 'inline'
          script: |
            # This is needed because some PM in Azure Dev Ops beleives that presenting Windows paths to bash is 
            # you know it... "Not a bug" ... way to go JR PM at MSFT ... way to have no clue what your market is.
            function wslpath() { 
              echo "$1" | sed -e 's|\\|/|g' -e 's|^\([A-Za-z]\)\:/\(.*\)|/\L\1\E/\2|'
            }
            function wslpath2 {
              while read data; do
                echo "$data" | sed -e 's|\\|/|g' -e 's|^\([A-Za-z]\)\:/\(.*\)|/\L\1\E/\2|' 
              done
            }
            
            TEMP_DIR="$(wslpath $AGENT_TEMPDIRECTORY)"
            # Locate all assemblies that need to be signed.  This is also the full list of generated assemblies
            # *1 = find all .sign files which are generated by build instructions in the Build.Directory.targets file
            # *2 = pipe the file path into a cat to pipe the file contents to the next command 
            # *3 = remove any CR characters from the file (linux/unix doesn't like them)
            # *4 = change single backslash to dual backslash for the next command to work properly 
            # *5 = these paths were generated by a windows process (msbuild) so they are DOS style paths ... 
            #      change them to linux paths
            # *6 = pipe the results into "$TEMP_DIR/assemblies.sign"
            #          *1         |     *2    |     *3           |        *4         |        *5            |           *6
            find . -name '*.sign' | xargs cat | sed -E 's/\r//g' | sed 's/\\/\\\\/g' | echo "$(wslpath2 %)" > "$TEMP_DIR/assemblies.sign"
            echo 'Located the following assemblies to sign'
            cat "$TEMP_DIR/assemblies.sign"

            # Strip out all path details so we have a list of only the assembly names (this is used for other tasks such as Nuget file generation)
            for file in $(cat "$TEMP_DIR/assemblies.sign" | sed -E 's/\r//g')
            do
            #   get the file name without path
                ASSM=$(basename $(wslpath "$file"))
            #   get the file name without extension (this should be the assembly name)
                echo ${ASSM%.*}
            # *1 = uniq the results so that the same assembly doesn't occur twice (this can happen with multi-target builds)
            # *2 = pipe the results into "$TEMP_DIR/assemblies.list"
            #       *1  |         *2
            done | uniq > "$TEMP_DIR/assemblies.list"
            cat "$TEMP_DIR/assemblies.list"

            # Locate all Assemblies that are going to be generating a NugetPackage (ones with <NugetPackage>True</NugetPackage> in them).
            # As this should never be set to "False", jsut the presence of NugetPackage in the csproj file is good to count it 
            # as a project neading package generation.
            # *1 = find all csprojs
            # *2 = Find only the ones with NugetPackage in them... return only the file name
            # *3 = pipe into a script which extractes only the file name without an extension   
            # *4 = pipe that into a new file "nuget.list" in the temp directory
            #       *1            |            *2                |                                        *3                                                                 |          *4
            find . -name *.csproj | xargs grep -l 'NugetPackage' | xargs -I + sh -c 'TEMP_VAR="+"; TEMP_VAR2="$(basename '+')"; echo "$(dirname $TEMP_VAR)/${TEMP_VAR2%.*}"' > "$TEMP_DIR/nuget.list"
            cat "$TEMP_DIR/nuget.list"

      - task: AzureKeyVault@1
        displayName: 'Azure Key Vault: landorphan-build'
        inputs:
          azureSubscription: 'Landorphan Holdings (1286ed67-15ce-4500-899e-e79313d8329f)'
          KeyVaultName: 'landorphan-build'
          SecretsFilter: 'LandorphanKeyVaultKey'

      - task: Bash@3
        displayName: 'Sign the resulting assembly files.'
        inputs:
          targetType: 'inline'
          script: |
            # This is needed because some PM in Azure Dev Ops beleives that presenting Windows paths to bash is 
            # you know it... "Not a bug" ... way to go JR PM at MSFT ... way to have no clue what your market is.
            function wslpath() { 
              echo "$1" | sed -e 's|\\|/|g' -e 's|^\([A-Za-z]\)\:/\(.*\)|/\L\1\E/\2|'
            }
            # Script a signing of all assemblies produced by the build.
            cat "$(wslpath $AGENT_TEMPDIRECTORY)/assemblies.sign" | xargs -I % "$(wslpath $AGENT_BUILDDIRECTORY)/d/azuresigntool.exe" sign "%" --file-digest sha256 --description-url "https://github.com/landorphan/service-location" --no-page-hashing --timestamp-rfc3161 http://timestamp.comodoca.com --timestamp-digest sha256 --azure-key-vault-url "https://landorphan-build.vault.azure.net/" --azure-key-vault-client-id "b32bbbae-55c3-4f5b-bf40-0292d349886f" --azure-key-vault-client-secret "$(LandorphanKeyVaultKey)" --azure-key-vault-certificate "Landorphan-LightWeight-CodeSign"
            echo 'Code sign job comlete'

      - task: Bash@3
        displayName: 'Generate Nuget Files'
        inputs:
          targetType: 'inline'
          script: |
            # This is needed because some PM in Azure Dev Ops beleives that presenting Windows paths to bash is 
            # you know it... "Not a bug" ... way to go JR PM at MSFT ... way to have no clue what your market is.
            function wslpath() { 
              echo "$1" | sed -e 's|\\|/|g' -e 's|^\([A-Za-z]\)\:/\(.*\)|/\L\1\E/\2|'
            }

            echo 'Nuget Generation Complete'

      - task: VSTest@2
        displayName: 'VsTest - testAssemblies'
        inputs:
          testAssemblyVer2: |
            **\$(BuildConfiguration)\**\*Tests.dll
            **\$(BuildConfiguration)\**\*Tests.*.dll
            !**\obj\**
          testFiltercriteria: '(TestCategory=Check-In|Check-In-Non-Ide)'
          codeCoverageEnabled: true
          platform: '$(BuildPlatform)'
          configuration: '$(BuildConfiguration)'
          diagnosticsEnabled: True
      
      - task: CopyFiles@2
        inputs:
          SourceFolder: '$(Agent.TempDirectory)'
          Contents: 'assemblies.sign'
          TargetFolder: '$(Build.ArtifactStagingDirectory)'

      - task: CopyFiles@2
        displayName: 'TEMP: Copy Files to: $(Build.ArtifactStagingDirectory)'
        inputs:
          SourceFolder: '$(system.defaultworkingdirectory)'
          Contents: '$(Build.SourcesDirectory)\**\bin\$(BuildConfiguration)\**'
          TargetFolder: '$(Build.ArtifactStagingDirectory)'


      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'